/*
-- Query: select * from alcohol_food_pairings
LIMIT 0, 1000

-- Date: 2021-04-22 00:09
*/
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('barolo','beef');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('barolo','duck');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('barolo','venison');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('beaujolais','feta');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('bordeaux','duck');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('bordeaux','venison');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cabernet sauvignon','beef');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cabernet sauvignon','duck');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cabernet sauvignon','gouda');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cabernet sauvignon','pepper jelly');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cabernet sauvignon','pork');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cabernet sauvignon','salsa');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cabernet sauvignon','soy');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cabernet sauvignon','venison');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('carlsberg','artichoke');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('carlsberg','mozzarella');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('carlsberg','sun dried tomatoes');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cava',' chorizo');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cava','beef');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cava','caviar');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cava','cod');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cava','fig');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cava','habanero');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cava','mushroom');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cava','pepperoni');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cava','pickled');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cava','salmon');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cava','sausage');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('cava','seafood');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('champagne',' chorizo');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('champagne',' cod');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('champagne',' cream');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('champagne',' gourmet');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('champagne',' pepperoni');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('champagne',' pickled');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('champagne',' salmon');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('champagne',' sausage');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('champagne',' seafood');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('champagne',' tuna');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('champagne','caviar');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('champagne','sweet');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chardonnay',' chicken');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chardonnay',' corn');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chardonnay',' courgette');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chardonnay',' gruyere');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chardonnay',' jerky');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chardonnay',' nut');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chardonnay',' pork');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chardonnay',' turkey');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chardonnay','seafood');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chardonnay','sour');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chenin blanc',' sour');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chenin blanc','habanero');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chenin blanc','salty');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chianti',' ragu');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chianti',' steak');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chianti','beef');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('chianti','piri piri');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('gewürztraminer',' sour');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('gewürztraminer','basil');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('gewürztraminer','haloumi');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('guinness','curry');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('guinness','ham');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('guinness','ranch');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('heineken',' salty');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('heineken',' spicy');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('heineken','danish');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' asian');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' berries');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' cheddar');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' cherry');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' ginger');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' ham');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' pastrami');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' pork');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' salmon');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' salty');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' spicy');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' tuna');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec',' venison');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('malbec','duck');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('merlot',' berries');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('merlot',' grilled');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('merlot',' ham');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('merlot',' monterey');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('merlot',' mushroom');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('merlot',' olives');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('merlot',' salmon');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('merlot',' satay');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('merlot',' steak');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('merlot',' tuna');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('merlot','lamb');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('muscat blanc',' sour');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('muscat blanc',' spicy');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('muscat blanc','salty');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio',' asian');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio',' blue cheese');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio',' chicken');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio',' coconut');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio',' crab');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio',' gorgonzola');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio',' gruyere');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio',' mozzarella');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio',' prawn');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio',' salmon');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio',' seafood');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio','stilton');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot grigio','tuna');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir',' mushroom');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir',' pastrami');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir',' pork');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir',' salmon');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir',' salty');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir',' spicy');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir',' tuna');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir',' venison');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir','asian');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir','berries');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir','brie');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir','cherry');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir','duck');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir','ginger');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('pinot noir','ham');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('port','blue cheese');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco',' cream');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco',' gourmet');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco',' parmesan');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco',' pepperoni');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco',' pickled');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco',' salmon');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco',' salty');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco',' sausage');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco','caviar');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco','chorizo');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco','cod');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco','seafood');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('prosecco','tuna');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('riesling','asparagus');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('riesling','barbecue');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('riesling','camembert');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('riesling','chorizo');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('riesling','french fries');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('riesling','ham');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('riesling','pepperoni');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('riesling','ricotta');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('riesling','salmon');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('riesling','sausage');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('riesling','seafood');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('riesling','shallots');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('rioja','capers');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('rioja','chorizo');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('rioja','lamb');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('rioja','tuna');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sancerre','asparagus');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sangiovese','beetroot');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sangiovese','chili');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauternes','gruyere');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauternes','swiss');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauvignon blanc','bell peppers');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauvignon blanc','goat');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauvignon blanc','lobster');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauvignon blanc','oyster');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauvignon blanc','peanuts');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauvignon blanc','pesto');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauvignon blanc','prawns');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauvignon blanc','pumpkin');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauvignon blanc','ragu');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauvignon blanc','sardines');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sauvignon blanc','spinach');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('sol','jalapeno');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('syrah','falafel');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('syrah','lamb');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('syrah','olives');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('syrah','pork');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('syrah','salsa');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('syrah','sausage');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('voignier','corn');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('zinfandel rosé','aioli');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('zinfandel rosé','avocado');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('zinfandel rosé','cherry tomatoes');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('zinfandel rosé','chicken');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('zinfandel rosé','ciabatta');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('zinfandel rosé','crab');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('zinfandel rosé','feta cheese');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('zinfandel rosé','garlic aioli');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('zinfandel rosé','puttenesca');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('zinfandel rosé','sardines');
INSERT INTO `` (`beverage_name`,`food_type`) VALUES ('zinfandel rosé','seafood');
