/*
-- Query: select * from namelets
LIMIT 0, 1000

-- Date: 2021-04-22 00:13
*/
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('alfredo sauce','butterfingers','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('alfredo sauce','buttery','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('amaretto','nutty','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('amaretto','roma','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('amaretto','sippetto','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('amaretto','tap shoe','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('anchovies','briny','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('anchovies','salty','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('apricot brandy','marmalade','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('apricot brandy','medicine','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('apricot brandy','orchird','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('artichoke hearts','cardiac','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('asparagus tips','arrowhead','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('asparagus tips','pointy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('avocado','californian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('avocado','new-age','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('baby corn','jolly green','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('baby corn','mayan','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('baby spinach','popeye\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bacon','heart-stopping','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bacon','porky','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bacon','sizzling','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bacon','zapatos','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('balsamic glaze','gourmet','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('balsamic glaze','vinegar','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('barbecue sauce','barbie doll','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('barbecue sauce','outdoors','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('basil pesto','fawlty','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bean curd','lumpy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bechamel sauce','creamy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('beef jerky','chewy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('beef jerky','extravagance','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('beef jerky','rubber','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('beetroot slices','red-faced','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bell peppers','bong','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bell peppers','ding-dong','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bell peppers','ringing','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bitter campari','agrieved','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bitter campari','grudge','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bitter campari','rosso','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bitter campari','tangy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('black olives','black-eyed','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('black olives','greek','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('black pudding','blackhole','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('black pudding','darth vader\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('black pudding','irish','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('blood sausage','bloody','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('blood sausage','tarantino\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('bolognese sauce','tuscan','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('boursin cheese','french, gallic','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('brie','french','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('button mushrooms','button-nosed','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('button mushrooms','fungi','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('camembert','french','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('canadian bacon','polite','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('capers','caped','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('carbonarra sauce','creamy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('carrot strips','buggs','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('carrot strips','bunny','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('caviar','czar\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('caviar','romanov','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('caviar','russian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cheddar','english','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cherry tomatoes','succulent','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cherry tomatoes','sundae','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chicken fajitas','mexican','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chicken fajitas','sizzling','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chicken fajitas','viva','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chicken fajitas','zinger','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chicken tikka','bollywood','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chicken tikka','maharaja\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chicken tikka','taj','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chickpeas','eastern','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chickpeas','levantine','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chilli con carne','mariachi','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chilli con carne','mexican','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chilli con carne','viva','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chimichurri sauce','argentine','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chimichurri sauce','gaucho','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chimichurri sauce','latin','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chopped garlic',' vampire hunter\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chopped garlic','van helsing\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chorizo','matador\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('chorizo','spanish','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('ciabatta','airy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('ciabatta','bubbly','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('coca cola','capitalist','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('coca cola','rocket','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('coconut curry sauce','thai','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cod goujons','atlantic','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cod goujons','bull','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('coffee liquer','alarm','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('coffee liquer','espresso','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('coffee liquer','java','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('coffee liquer','wake up','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cognac','baguette','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cognac','chez','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cognac','corker','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cognac','froggy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cottage cheese','lumpy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('crab meat','mr. krab\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('crab meat','pearl','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cracker crust','cracker','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cracker crust','crunchy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cranberries','christmas','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cranberry juice','berrylicious','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cranberry juice','burst','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('cranberry juice','purple','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('curried chicken','bollywood','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('curried chicken','maharaja\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('curried chicken','palace','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('curried chicken','taj','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('curry sauce','bombay','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('curry sauce','taj','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('danish blue cheese','indigo','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('danish blue cheese','smurf','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('danish blue cheese','ultraviolet','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('deep dish crust','mattress','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('deep dish crust','phonebook','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('deep dish crust','spongy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('deep-fried base','heart attack','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('dry martini','double  o seven','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('dry martini','martin’s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('edam','double dutch','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('edam','dutch','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('edam','red light','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('falafel','aladin\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('falafel','baghdad','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('falafel','eastern','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('fernet branca','spice bag','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('fernet branca','twiggy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('feta cheese','acropolis','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('feta cheese','athenian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('feta cheese','greek','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('feta cheese','parthenon','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('feta cheese','zorba’s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('fig jam','wrinkled','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('filet mignon','kroner','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('filet mignon','millionaire\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('filet mignon','ooh la la','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('flatbread','flat-capped','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('flatbread','flat-footed','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('focaccia ','astroturf','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('focaccia ','fluffy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('french fries','crunchy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('french fries','golden','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('french fries','happy meal','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('french onions','eye-watering','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('french onions','parisien','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('garlic aioli sauce','beverly hills','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('garlic aioli sauce','west-coast','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gin','gin-a-ling','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gin','kick','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gluten-free crust','frisbee','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gluten-free crust','poor man\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('goat\'s cheese','billy goat','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('goat\'s cheese','headbutt','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('goat\'s cheese','ram','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('goat\'s cheese','stubborn','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gorgonzola','italian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gorgonzola','skunk','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gorgonzola','smelly','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gouda','double dutch','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gouda','dutch','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gouda','red light','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('green olives','club med','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('green olives','martini','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('green olives','mediterranean','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('grenadine syrup','shirley’s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('grenadine syrup','toothache','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('grilled apricots','fruity','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('grilled apricots','tiger','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('grilled chicken','flaming','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('grilled chicken','spongebob','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('grilled chicken','sun-tanned','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gruyere','alpine','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gruyere','banker\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gruyere','fondue','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('gyro bread','bendy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('habanero chillis','burning','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('habanero chillis','exploding','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('habanero chillis','explosive','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('habanero chillis','thermonuclear','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('habanero chillis','volcano','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('haloumi cheese','cypriot','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('ham hock','chubby','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('ham hock','peppa','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('ham hock','porky','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('harissa sauce','moroccan','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('hoisin sauce','peking','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('hummus','levantine','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('hummus','moroccan','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('jalapeno jack','jumpin\'','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('jalapenos','burning','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('jalapenos','exploding','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('jalapenos','explosive','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('jalapenos','feisty','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('jalapenos','fire, tnt','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('jarlsberg cheese','bismarck\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('jarlsberg cheese','blitzkrieg','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('kimchi','korean','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('kimchi','m*a*s*h','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('kimchi','sour','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('king prawns','deep-sea','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('king prawns','neptune\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('king prawns','regal','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('king prawns','royal','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('kobe beef','godzilla\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('kobe beef','yokohama','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('korean beef','bull','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('korean beef','kim jung','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('korean beef','oriental','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('korean beef','spicy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('lamb kofta','bo peep\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('lamb kofta','moroccan','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('lamb kofta','woolly','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('lemon juice','grimace','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('lemon juice','sour','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('lemon juice','squeeze','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('lemon juice','yellow','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('lime juice','gogo','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('lime juice','green','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('lime juice','rind','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('lime juice','zingy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('lobster tail','neptune\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('manchego cheese','bullfight','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('manchego cheese','quixote\'s, franco\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('maraschino luxardo','diamond','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('maraschino luxardo','lux','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('maraschino luxardo','tuxedo','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('marinara sauce','neopolitan','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('meatballs','carnivorous','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('mongolian beef','genghis','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('mongolian beef','khan\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('monterey jack','fully monty','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('monterey jack','yankee, ','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('mozzarella','buffalo','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('multigrain crust','farmhouse','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('multigrain crust','rustic','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('munster cheese','herman\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('munster cheese','monster','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('olive tapenade','spanish','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('olive tapenade','tap dance','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('orange segments','florida','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('orange segments','sunshine','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('paneer cheese','clotted','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('paneer cheese','indian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('parma ham','italian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('parma ham','undercooked','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('parmesan cheese','grand','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('parmesan cheese','padano','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pastrami','brooklyn','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pastrami','new york','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('peking duck','bambi','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('peking duck','peking','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pepper jelly','gourmet','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pepper jelly','knightsbridge','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pepperoni','italian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pepperoni','spicy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pickled onions','sour-faced','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pine nuts','roman','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('piri piri sauce','red hot','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('piri piri sauce','sizzling','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pistachios','greek','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pistachios','nutty','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('polenta crust','corn-fed','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('polenta crust','italian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('porcini mushrooms','forest','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('porcini mushrooms','fungi','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('port salut cheese','iberian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('portobello mushrooms','flat-capped','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('portobello mushrooms','fungi','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('prosecco','bubbly','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('prosecco','fizzy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('prosecco','glimmer','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('provolone','lothario','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('provolone','provincial','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('provolone','rustic','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('puff pastry','cloud','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('puff pastry','flaky','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('puff pastry','staypuft','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pulled pork','peppa','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pulled pork','porky','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pumpkin chunks','autumn','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pumpkin chunks','halloween','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('pumpkin chunks','jack-o-lantern','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('puttenesca sauce','midnight','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('puttenesca sauce','streetwalker','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('quark','teutonic','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('queso fresco','mexican, viva, mariachi','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('quorn chunks','cave wall','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('ragu','raging','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('raised crust','elevator','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('raised crust','high rise','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('raised crust','puffy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('raisins','mummy','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('raisins','wrinkled','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('ranch sauce','buckaroo','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('ranch sauce','cowboy','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('ranch sauce','western','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('red leicester','crimson','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('red onions','red-eye','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('red peppers','striped','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('ricotta cheese','cheesecake','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('ricotta cheese','italian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('roast beef','codpiece','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('roast beef','john bull\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('roast turkey','festive','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('salami','italian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('salami','oily','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('salsa','dancin\'','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sardines','tinned','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('satay sauce','malay','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sauerkraut','bavarian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sauerkraut','teutonic','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sausage','juicy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sausage','porky','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('scotch whisky','bog','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('scotch whisky','kilt','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('scotch whisky','sheep','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('scotch whisky','tartan','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('seared scallops','aphrodite\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('shallots','parisien','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('shiitake mushrooms','asian','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('shiitake mushrooms','fungi','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sliced aubergine','auberge','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sliced aubergine','club med','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sliced aubergine','mediterranean','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sliced courgettes','green-eyed','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sliced courgettes','mediterranean','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sliced green tomatoes','southern','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('smoked salmon','tycoon\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('smoked tofu','coughing','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('soda water','nonna’s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('soda water','river','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sourdough crust','fermented','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sourdough crust','vinegar','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('soy cheese','artificial, synthetic','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('soy chunks','synthetic','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('soy-miso sauce','edo','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('soy-miso sauce','geisha','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('soy-miso sauce','samurai','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('soy-miso sauce','tokyo','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('spam','canned','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('spam','monty python\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('steak','chewtoy','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('steak','steakhouse','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('stilton','blue-veined','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('stilton','english','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('stuffed crust','stuffed','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sun-dried tomatoes','mummified','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('swedish meatballs','abba','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('swedish meatballs','ikea','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('swedish meatballs','naked','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweet and sour chicken','bipolar','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweet and sour chicken','moody','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweet and sour chicken','oriental','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweet and sour chicken','palace','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweet and sour pork','bipolar','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweet and sour pork','moody','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweet and sour pork','oriental','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweet red vermouth','bonbon','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweet red vermouth','candy’s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweet red vermouth','grin','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweet red vermouth','stop light','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweetcorn','jolly green','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('sweetcorn','mayan','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('swiss cheese','alpine','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('swiss cheese','apres ski','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('swiss cheese','avalanche,','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('swiss cheese','cuckoo','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('swiss cheese','heidi\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('swiss cheese','neutral','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('taco beef','mexican','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('taco beef','seoulmate','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('taco beef','viva','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('tandoori chicken','bollywood','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('tandoori chicken','flaming','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('tandoori chicken','maharaja\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('tandoori chicken','taj','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('tequila','gamble','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('tequila','pedro’s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('tequila','sombrero','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('tequila','taco','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('thai chili sauce','emperor','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('thai chili sauce','siamese','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('thick crust','mantle','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('thick crust','mouthful','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('thick crust','slab','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('thin crust','crispy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('thin crust','platter','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('thin crust','skinny','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('toasted almonds','nutty','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('tofu cubes','synthetic','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('tomato pesto','tuscan','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('triple sec','coupe','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('triple sec','macron’s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('triple sec','sacré','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('triple sec','tripletto','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('truffle shavings','millionaire\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('truffle shavings','razor','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('truffle shavings','rich man\'s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('tuna','atlantic','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('tuna','pacific','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('unleavened crust ','communion','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('unleavened crust ','flat-footed','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('vodka','babushka','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('vodka','burning','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('vodka','putin’s','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('wensleydale','grommit','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('wensleydale','yorkshire','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('white peach puree','pithy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('white peach puree','snowy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('white peach puree','tang','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('white rum','sippin’','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('white rum','snowman','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('white rum','yummy','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('wholewheat crust','farmhouse','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('wholewheat crust','rustic','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('wholewheat crust','unrefined','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('wilted greens','sauna','after');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('wilted greens','sweaty','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('zaatar and olive oil','eastern','before');
INSERT INTO `` (`ingredient_id`,`namelet`,`namelet_position`) VALUES ('zaatar and olive oil','moroccan','before');
